Enable Stylus support
dojo/cli-css-typings pull request #5
Opened 2016-11-11 19:03 UTC by bitpshr

Adds a `--stylus` option so typings can be generated for CSS modules written in Stylus

2016-11-29 12:23 UTC, tomdye requested changes

2016-11-29 12:23 UTC, Tomdye commented on src/generateTypings.ts
> +function compileStylus(content: string): Promise<string> {
Would be good to walk through this with you to see how the process fits together, would this not be better in a `compileStylus` file? Doesn't seem like a direct concern of `generateTypings`. Though that's just my opinion.

2016-11-29 12:23 UTC, Tomdye commented on src/generateTypings.ts
> +				return;
no need to return here

2016-11-29 12:23 UTC, Tomdye commented on tests/unit/main.ts
> +		const writeFileStub: sinon.SinonStub = sandbox.stub(fs, 'writeFile', function (name: string, content: string, done: Function) {
might look a bit tidier if you imported `{ SinonStub }` from sinon as well as the default.

2016-12-05 09:04 UTC, agubler commented
@Tomdye have your review feedback been addressed?

2017-01-27 13:51 UTC, dylans commented
Given switch to postcss, closing this out.

2017-01-27 13:51 UTC, closed without merging